# Configuration file for MegaLinter
# See all available variables at https://megalinter.io/configuration/ and in linters documentation

APPLY_FIXES: all
ENABLE_LINTERS:
  - GO_REVIVE
  - EDITORCONFIG_EDITORCONFIG_CHECKER
  - MARKDOWN_MARKDOWNLINT
  - BASH_SHELLCHECK
SHOW_ELAPSED_TIME: true
FILEIO_REPORTER: false
