version: "3"

tasks:
  default:
    desc: Display available tasks
    cmds:
      - task -l
  lint:
    desc: Run MegaLinter
    cmds:
      - mega-linter-runner --flavor go
  vhs:
    desc: Run VHS
    cmds:
      - vhs < img/demo.tape

  credits:
    desc: update credits
    cmds:
      - gocredits . > CREDITS
      
